### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException

### ISSUE THREAD

**Issue by serpro69** [serpro69/kotlin-faker#79]
Probably introduced in #70 when shadowing jackson.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:465)
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:368)
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15)
	at faker.com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1048)
	at faker.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1426)
	at io.github.serpro69.kfaker.Mapper.readValue(Mapper.kt:15)
	at io.github.serpro69.kfaker.FakerService.readCategory(FakerService.kt:167)
	at io.github.serpro69.kfaker.FakerService.load(FakerService.kt:65)
	at io.github.serpro69.kfaker.FakerService.<init>(FakerService.kt:32)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:14)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:13)
	at TestMeKt.main(TestMe.kt:4)
	at TestMeKt.main(TestMe.kt)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 13 more
```
